export default {
  Base: '/api',
  Users: {
    Base: '/users',
    GetAll: '/',
    Get: '/:id',
    Me: '/me',
    Add: '/',
    Update: '/:id',
    Delete: '/:id',
    ParentLock: {
      Base: '/parent-lock',
      Get: '/validate/:pin',
      Add: '/',
      Update: '/',
      Delete: '/',
    },
  },
  Accounts: {
    Base: '/accounts',
    GetAll: '/',
    Get: '/:id',
    Add: '/',
    Update: '/:id',
    Delete: '/:id',
  },
  Periodics: {
    Base: '/periodics',
    GetAll: '/',
    Get: '/:id',
    Add: '/',
    Update: '/:id',
    Delete: '/:id',
  },
  Tasks: {
    Base: '/tasks',
    GetAll: '/',
    Get: '/:id',
    Add: '/',
    Update: '/:id',
    Delete: '/:id',
  },
  Cron: {
    Base: '/cron',
    RunDaily: '/run-daily',
  },
} as const;
